version: "3.8"

services:
  # Your Node.js API
  backend:
    image: resume-server
    build: ./resume-parser-node # Path to your server folder
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      # Add other ENVs here (DB_URL, etc.)

  # Your Next.js Frontend
  frontend:
    image: resume-client
    build: ./resumeai-pro # Path to your client folder
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5050
    depends_on:
      - backend
